### ISSUE TITLE
exit status 1; not expected

### ISSUE THREAD

**Issue by whybangbang** [mnaberez/supervisor_twiddler#9] opened 2017-08-27 23:24 UTC
by twiddler run a program will get exited: task_comment_test (exit status 1; not expected) error , but if i config the same config in supervisord.conf, it's ok.
supervisor version is 3.3.3

**Comment by mnaberez** [comment] 2017-12-16 01:40
I've tried adding various program configurations with this plugin and was not able to duplicate this report.  I'm going to close this issue for now.  If you can send instructions for how to reproduce a bug, we can reopen.

This plugin takes config info from RPC and [stuffs it](https://github.com/mnaberez/supervisor_twiddler/blob/1.0.0/supervisor_twiddler/rpcinterface.py#L154-L157) into a `ConfigParser` instance, then asks `supervisord` to parse it.  All the same machinery inside `supervisord` is used as if the info came from a config file on disk.  Due to the way it works, this plugin shouldn't produce results different than a config file loaded from disk.

**Closed by mnaberez** 2017-12-16 01:40 UTC
